# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-07 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.IntegerField(verbose_name='\u7248\u672c\u53f7')),
                ('version_name', models.CharField(default='', max_length=16, verbose_name='\u7248\u672c\u540d\u79f0')),
                ('describe', models.CharField(default='\u65e0\u8bf4\u660e', max_length=256, verbose_name='\u63cf\u8ff0')),
                ('release', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53d1\u5e03')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': 'APP\u7248\u672c',
                'verbose_name_plural': 'APP\u7248\u672c',
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('school_class', models.CharField(default='', max_length=128, verbose_name='\u8bfe\u8868\u6240\u5c5e')),
                ('share', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5206\u4eab')),
                ('share_id', models.CharField(max_length=32, null=True, verbose_name='\u5206\u4eabid')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u8bfe\u7a0b\u7ec4',
                'verbose_name_plural': '\u8bfe\u7a0b\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('teacher', models.CharField(default='', max_length=32, verbose_name='\u8001\u5e08')),
                ('location', models.CharField(default='', max_length=128, verbose_name='\u4e0a\u8bfe\u5730\u70b9')),
                ('color', models.IntegerField(default=2290649224, verbose_name='\u989c\u8272')),
                ('time_which_day', models.IntegerField(verbose_name='\u5468\u51e0')),
                ('time_all_week', models.CharField(default='-', max_length=512, verbose_name='\u5468 \u7a7a\u4ee3\u8868\u6240\u6709')),
                ('start_node', models.IntegerField(verbose_name='\u5f00\u59cb\u8282\u6570')),
                ('node_count', models.IntegerField(verbose_name='\u603b\u8282\u6570')),
                ('only_id', models.CharField(default='', max_length=32, verbose_name='\u552f\u4e00\u6807\u8bc6')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CourseGroup', verbose_name='\u6240\u5c5e\u7ec4')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
    ]
